# Generated by Django 6.0.1 on 2026-01-17 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('UPLOAD', 'File Uploaded'), ('DELETE', 'File Deleted'), ('RESTORE', 'File Restored'), ('SHARE', 'File Shared'), ('LOGIN', 'User Login'), ('SUBSCRIPTION', 'Subscription Updated')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
