# Generated by Django 6.0.1 on 2026-01-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('uptime', models.FloatField(default=99.8)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('color', models.CharField(default='#e8d7ff', max_length=20)),
            ],
        ),
    ]
