# Generated by Django 6.0.1 on 2026-01-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
